{
  "hash": "27e063717a8ce85ee53bc488726f22b7",
  "result": {
    "markdown": "---\ntitle: \"Probability Theory\"\nauthor: \"akash.yadav `<akash.yadav@tuhh.de>`\"\ncode-fold: false \ncode-line-numbers: true\ncode-annotations: hover\ncode-summary: \"Expand To view the code\"\n---\n\n\n------------------------------------------------------------------------\n\n# Assignment 1\n\n::: {.callout-important title=\"Problem\"}\nDefine being on time as event `T` , being not on time as`~T` and having a change in scope as `S` and having no change in scope as `~S`\n:::\n\n##### Probability Tree\n\n\n```{mermaid}\ngraph LR;\n    classDef teal fill:teal;\n    classDef orange fill:orange;\n    Start((\" O \")) --> |0.3| Option1((\"S\"))\n    Start -->|0.7| Option2((\"~S\"))\n    Option1 -->|0.2| SubOption1((\"T\"))\n    SubOption1 -->|\"P(S ∩ T)\"| Final1[0.06]\n    Option1 -->|0.8| SubOption2((\"~T\"))\n    SubOption2 -->|\"P(S ∩ ~T)\"| Final2[0.24]\n    Option2 -->|0.6| SubOption3((\"T\"))\n    SubOption3 -->|\"P(~S ∩ T)\"| Final3[0.42]\n    Option2 -->|0.4| SubOption4((\"~T\"))\n    SubOption4 -->|\"P(~S ∩ ~T)\"| Final4[0.28]\n    class Option1 teal;\n    class SubOption1 orange;\n    class Option2 teal\n    class SubOption2 orange\n    class SubOption3 orange\n    class SubOption4 orange\n```\n\n{{< pagebreak >}}\n\n\n##### Code Snippet\n\n::: {.callout-tip title=\"code in R \"}\nSolving Conditional Events in R give `p_S` , `p_T_given_S`, `p_T_given_not_S`\n:::\n\n\n{{< pagebreak >}}\n\n\n::: {.cell hash='01_probability_cache/html/unnamed-chunk-2_b31728cf55e315a9cfa8c425bc3fad74'}\n\n```{.r .cell-code}\n# Define the probabilities\np_S <- 0.3  # Probability of Change in Scope\np_T_given_S <- 0.2  # Probability of Being On Time given Change in Scope\np_T_given_not_S <- 0.6  # Probability of Being On Time given No Change in Scope\n\n# Calculate the probabilities of combined events\np_S_and_T <- p_S * p_T_given_S\np_S_and_not_T <- p_S * (1 - p_T_given_S)\np_not_S_and_T <- (1 - p_S) * p_T_given_not_S\np_not_S_and_not_T <- (1 - p_S) * (1 - p_T_given_not_S)\n\n# Calculate the total probability\ntotal_prob <- p_S_and_T + p_S_and_not_T + p_not_S_and_T + p_not_S_and_not_T\n\n# Create a table of probabilities\nprob_table <- data.frame(\n  Event = c(\"S and T\", \"S and ~T\", \"~S and T\", \"~S and ~T\", \"Total\"),\n  Probability = c(p_S_and_T, p_S_and_not_T, p_not_S_and_T, p_not_S_and_not_T, total_prob)\n)\nprint(prob_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#>       Event Probability\n#> 1   S and T        0.06\n#> 2  S and ~T        0.24\n#> 3  ~S and T        0.42\n#> 4 ~S and ~T        0.28\n#> 5     Total        1.00\n```\n:::\n\n```{.r .cell-code}\nprint(paste(\"Total Probability: \", total_prob))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] \"Total Probability:  1\"\n```\n:::\n:::\n\n\n\n# Assignment 2\n\n:::{.callout-important title=\"Problem\"}\n**Using the Venn diagram above, answer the following questions.**\n\n- What is the percentage of customers using all three devices?\n\n- What is the percentage of customers using at least two devices?\n\n- What is the percentage of customers using only one device?\n:::\n\n\n\n::: {.cell hash='01_probability_cache/html/unnamed-chunk-3_cf586460d3b1c7625ee74f683b4242ae'}\n\n```{.r .cell-code}\n# Define probabilities for using devices\np_s <- 0.423\np_t <- 0.278\np_c <- 0.1\n\n# Calculate probability of using all three devices\np_stc <- p_s * p_t * p_c\n\n# Calculate probability of using at least two devices\np_at_least_two <- p_stc + p_s * p_t + p_s * p_c + p_t * p_c\n\n# Calculate probability of using only one device\np_one <- 1 - (p_stc + p_at_least_two)\n\ncat('Percentage of customers using all three devices:', round(100 * p_stc, 2), '%\\n')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> Percentage of customers using all three devices: 1.18 %\n```\n:::\n\n```{.r .cell-code}\ncat('Percentage of customers using at least two devices:', round(100 * p_at_least_two, 2), '%\\n')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> Percentage of customers using at least two devices: 19.95 %\n```\n:::\n\n```{.r .cell-code}\ncat('Percentage of customers using only one device:', round(100 * p_one, 2), '%\\n')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> Percentage of customers using only one device: 78.88 %\n```\n:::\n:::\n\n::: {.cell hash='01_probability_cache/html/unnamed-chunk-4_2ed9b75b59bd328f3740773ef242855b'}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\n# Define probabilities for using devices\np_s <- 0.423\np_t <- 0.278\np_c <- 0.1\n\n# Calculate probability of using all three devices\np_stc <- p_s * p_t * p_c\n\n# Calculate probability of using at least two devices\np_at_least_two <- p_stc + p_s * p_t + p_s * p_c + p_t * p_c\n\n# Calculate probability of using only one device\np_one <- 1 - (p_stc + p_at_least_two)\n\ndevice_usage <- data.frame(\n  device = c('All Three Devices', 'At Least Two Devices', 'Only One Device'),\n  count = c(p_stc, p_at_least_two, p_one)\n)\n\ndevice_usage$percentage <- device_usage$count * 100\n\nggplot(device_usage, aes(x = device, y = percentage, fill = device)) +\n  geom_bar(stat = \"identity\") +\n  theme_light() +\n  scale_fill_discrete(labels = c('All Three Devices', 'At Least Two Devices', 'Only One Device')) +\n  labs(\n    title = \"Percentage of Customers Using Different Device Combinations\",\n    subtitle = \"Device Usage Distribution\",\n    fill = \"Device Combination\"\n  )\n```\n\n::: {.cell-output-display}\n![](01_probability_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\n# Assignment 3\n\n:::{.callout-important title=\"Problem\"}\n- P(\\bar{A}|B)(1)\n- P(A|B)(2)\nand fill the gaps in the following sentence:\n\nThese results show that in case the alarm is triggered, there is a possibility of about __% that the product is flawless and a probability of __% that the product is faulty.\n:::\n\n\n::: {.cell hash='01_probability_cache/html/unnamed-chunk-5_c0086dab8a2c54c3b16338da0a18dec5'}\n\n```{.r .cell-code}\n# Define probabilities\np_a <- 0.04\np_b_given_a <- 0.97\np_b_given_not_a <- 0.01\n\n# Calculate probabilities of product being flawless and faulty given alarm triggered\np_not_a_given_b <- (p_b_given_not_a * (1 - p_a)) / (p_b_given_a * p_a + p_b_given_not_a * (1 - p_a))\np_a_given_b <- (p_b_given_a * p_a) / (p_b_given_a * p_a + p_b_given_not_a * (1 - p_a))\n\nproduct_condition <- c('Product is Flawless', 'Product is Faulty')\nprobabilities <- c(p_not_a_given_b * 100, p_a_given_b * 100)\ncolors <- c('skyblue', 'coral')\n\nproduct_condition_probabilities <- data.frame(\n  product_condition = product_condition,\n  probability = probabilities,\n  color = colors\n)\n\nprint(data.frame(product_condition=product_condition,probability = probabilities))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#>     product_condition probability\n#> 1 Product is Flawless    19.83471\n#> 2   Product is Faulty    80.16529\n```\n:::\n\n```{.r .cell-code}\nggplot(product_condition_probabilities, aes(x = product_condition, y = probability, fill = color)) +\n  geom_bar(stat = \"identity\") +\n  theme_light() +\n  scale_fill_discrete(labels = c('Product is Flawless', 'Product is Faulty')) +\n  labs(\n    title = \"Probability of Product Condition Given Alarm Triggered\",\n    subtitle = \"Product Flawless vs. Faulty\",\n    x = \"Product Condition\",\n    y = \"Probability\"\n  )\n```\n\n::: {.cell-output-display}\n![](01_probability_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n:::{.callout-tip title=\"Solution\"}\nThese results show that in case the alarm is triggered, there is a possibility of about `19.83471%` that the product is flawless and a probability of `80.16529%` that the product is faulty.\n:::",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}